### ISSUE TITLE
💄 style: 누끼딴 Neolun 이미지 DB 업데이트 필요

### ISSUE THREAD

**Issue by redcontroller** [FRONTENDSCHOOLPLUS2/hyundai-morgans#35]
## 📏구현 및 수정 기능

- 임시로 넣은 Neolun 이미지를 대체할 png 파일 업로드 필요
- 다른 차량의 이미지와 같은 스펙으로 만들어야 함

## 📝 상세 작업 내용
 - [x] Neolun 누끼 이미지 작업
 - [x] dbinit 수행
 - [x] 실제 프로젝트 실행해서 바뀐 이미지 확인

## 📄 참고 사항
레이아웃이 틀어지지 않도록 다른 차량의 이미지와 같은 스펙으로 만들어야 함!!

**Comment by ryungom** [comment]
api 레포지토리에 Neolun 누끼이미지 작업 완료 후 해당 작업 수행 완료했습니다~!

**Comment by redcontroller** [comment]
자연스럽게 누끼 따주셔서 감사해요!

![image](https://github.com/user-attachments/assets/4b85d6c1-785a-40d6-95ae-c268f91c8e28)
